# Consumer Price Index 

The datasets represented in this jupyter notebook are from the Bureau of Labor Statistics:
 - [Top Picks for Consumer Prices](https://data.bls.gov/cgi-bin/surveymost?ap)

This dataset represents consumer prices that are common purchases for the United States populace. Having a reflection of price changes throughout the last two decades will help glean insights into what changes in pricing do to over consumer sentiment in the economy. Below you will find a wrangling process to clean a dataset that will be joined to consumer sentiment index, inflation, and energy information to determine a narrow, but holistic review of consumer sentiment sensitivity.

In [2]:
# Libraries used for this wrangling effort.

import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
from datetime import date

Loading the dataset into the cpi variable

In [6]:
cpi = pd.read_csv(r'C:\Users\stanl\OneDrive\Documents\Graduate School\Regis_Practicum_1\CPI Average Price Data.csv')

In [7]:
# previewing the data
cpi.head()

,Date,APU0000704111 Original Data Value,APU0000704111 1-Month Percent Change,APU0000704111 3-Month Percent Change,APU0000704111 12-Month Percent Change,APU0000711211 Original Data Value,APU0000711211 1-Month Percent Change,APU0000711211 3-Month Percent Change,APU0000711211 12-Month Percent Change,APU0000702111 Original Data Value,...,APU000072511 3-Month Percent Change,APU000072511 12-Month Percent Change,APU00007471A Original Data Value,APU00007471A 1-Month Percent Change,APU00007471A 3-Month Percent Change,APU00007471A 12-Month Percent Change,APU000074714 Original Data Value,APU000074714 1-Month Percent Change,APU000074714 3-Month Percent Change,APU000074714 12-Month Percent Change
0,1990-01-01,1.966,0.5,11.2,8.9,0.429,3.1,-0.7,8.9,0.689,...,41.9,42.6,1.090,5.8,1.8,15.5,1.042,6.3,1.5,13.5
1,1990-02-01,2.009,2.2,10.4,11.7,0.492,14.7,13.1,18.6,0.701,...,12.0,15.2,1.086,-0.4,3.8,13.7,1.037,-0.5,3.8,12.0
2,1990-03-01,1.991,-0.9,1.8,11.4,0.500,1.6,20.2,11.1,0.680,...,0.9,10.8,1.076,-0.9,4.5,10.5,1.023,-1.4,4.4,8.8
3,1990-04-01,1.979,-0.6,0.7,13.3,0.481,-3.8,12.1,-8.0,0.686,...,-23.1,7.1,1.096,1.9,0.6,-0.2,1.044,2.1,0.2,-2.0
4,1990-05-01,2.044,3.3,1.7,21.7,0.462,-4.0,-6.1,-11.5,0.678,...,-6.9,7.3,1.114,1.6,2.6,-3.3,1.061,1.6,2.3,-5.2

Checking shape - there are 384 rows, 61 columns

In [8]:
cpi.shape

(384, 61)

In [5]:
cpi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384 entries, 0 to 383
Data columns (total 61 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Date                                   384 non-null    object
 1   APU0000704111 Original Data Value      381 non-null    float64
 2   APU0000704111 1-Month Percent Change   381 non-null    float64
 3   APU0000704111 3-Month Percent Change   381 non-null    float64
 4   APU0000704111 12-Month Percent Change  381 non-null    float64
 5   APU0000711211 Original Data Value      381 non-null    float64
 6   APU0000711211 1-Month Percent Change   381 non-null    float64
 7   APU0000711211 3-Month Percent Change   381 non-null    float64
 8   APU0000711211 12-Month Percent Change  381 non-null    float64
 9   APU0000702111 Original Data Value      381 non-null    float64
 10  APU0000702111 1-Month Percent Change   381 non-null    float64
 11  APU0000702111 3-Month Percent Change   381 non-null    float64
 12  APU0000702111 12-Month Percent Change  381 non-null    float64
 13  APU0000706111 Original Data Value      380 non-null    float64
 14  APU0000706111 1-Month Percent Change   379 non-null    float64
 15  APU0000706111 3-Month Percent Change   379 non-null    float64
 16  APU0000706111 12-Month Percent Change  379 non-null    float64
 17  APU0000717311 Original Data Value      341 non-null    float64
 18  APU0000717311 1-Month Percent Change   337 non-null    float64
 19  APU0000717311 3-Month Percent Change   333 non-null    float64
 20  APU0000717311 12-Month Percent Change  317 non-null    float64
 21  APU0000708111 Original Data Value      381 non-null    float64
 22  APU0000708111 1-Month Percent Change   381 non-null    float64
 23  APU0000708111 3-Month Percent Change   381 non-null    float64
 24  APU0000708111 12-Month Percent Change  381 non-null    float64
 25  APU0000701111 Original Data Value      380 non-null    float64
 26  APU0000701111 1-Month Percent Change   379 non-null    float64
 27  APU0000701111 3-Month Percent Change   379 non-null    float64
 28  APU0000701111 12-Month Percent Change  379 non-null    float64
 29  APU0000709112 Original Data Value      315 non-null    float64
 30  APU0000709112 1-Month Percent Change   314 non-null    float64
 31  APU0000709112 3-Month Percent Change   312 non-null    float64
 32  APU0000709112 12-Month Percent Change  303 non-null    float64
 33  APU0000711311 Original Data Value      295 non-null    float64
 34  APU0000711311 1-Month Percent Change   274 non-null    float64
 35  APU0000711311 3-Month Percent Change   243 non-null    float64
 36  APU0000711311 12-Month Percent Change  280 non-null    float64
 37  APU0000701312 Original Data Value      356 non-null    float64
 38  APU0000701312 1-Month Percent Change   354 non-null    float64
 39  APU0000701312 3-Month Percent Change   352 non-null    float64
 40  APU0000701312 12-Month Percent Change  343 non-null    float64
 41  APU0000712311 Original Data Value      378 non-null    float64
 42  APU0000712311 1-Month Percent Change   376 non-null    float64
 43  APU0000712311 3-Month Percent Change   375 non-null    float64
 44  APU0000712311 12-Month Percent Change  375 non-null    float64
 45  APU000072610 Original Data Value       381 non-null    float64
 46  APU000072610 1-Month Percent Change    381 non-null    float64
 47  APU000072610 3-Month Percent Change    381 non-null    float64
 48  APU000072610 12-Month Percent Change   381 non-null    float64
 49  APU000072511 Original Data Value       381 non-null    float64
 50  APU000072511 1-Month Percent Change    381 non-null    float64
 51  APU000072511 3-Month Percent Change    381 non-null    float64
 52  APU000072511 12-Month Percent Change   381 non-null    float64
 53  APU00007471A Original Data Value       381 non-null    float64
 54  APU00007471A 1-Month Percent Change    381 non-null    float64
 55  APU00007471A 3-Month Percent Change    381 non-null    float64
 56  APU00007471A 12-Month Percent Change   381 non-null    float64
 57  APU000074714 Original Data Value       381 non-null    float64
 58  APU000074714 1-Month Percent Change    381 non-null    float64
 59  APU000074714 3-Month Percent Change    381 non-null    float64
 60  APU000074714 12-Month Percent Change   381 non-null    float64
dtypes: float64(60), object(1)
memory usage: 183.1+ KB

Checking with .info() we see that float datatypes are present and that the date is still a string object that will need to be addressed.

In [9]:
cpi['Date'] = pd.to_datetime(cpi['Date'])

In [11]:
cpi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384 entries, 0 to 383
Data columns (total 61 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Date                                   384 non-null    datetime64[ns]
 1   APU0000704111 Original Data Value      381 non-null    float64
 2   APU0000704111 1-Month Percent Change   381 non-null    float64
 3   APU0000704111 3-Month Percent Change   381 non-null    float64
 4   APU0000704111 12-Month Percent Change  381 non-null    float64
 5   APU0000711211 Original Data Value      381 non-null    float64
 6   APU0000711211 1-Month Percent Change   381 non-null    float64
 7   APU0000711211 3-Month Percent Change   381 non-null    float64
 8   APU0000711211 12-Month Percent Change  381 non-null    float64
 9   APU0000702111 Original Data Value      381 non-null    float64
 10  APU0000702111 1-Month Percent Change   381 non-null    float64
 11  APU0000702111 3-Month Percent Change   381 non-null    float64
 12  APU0000702111 12-Month Percent Change  381 non-null    float64
 13  APU0000706111 Original Data Value      380 non-null    float64
 14  APU0000706111 1-Month Percent Change   379 non-null    float64
 15  APU0000706111 3-Month Percent Change   379 non-null    float64
 16  APU0000706111 12-Month Percent Change  379 non-null    float64
 17  APU0000717311 Original Data Value      341 non-null    float64
 18  APU0000717311 1-Month Percent Change   337 non-null    float64
 19  APU0000717311 3-Month Percent Change   333 non-null    float64
 20  APU0000717311 12-Month Percent Change  317 non-null    float64
 21  APU0000708111 Original Data Value      381 non-null    float64
 22  APU0000708111 1-Month Percent Change   381 non-null    float64
 23  APU0000708111 3-Month Percent Change   381 non-null    float64
 24  APU0000708111 12-Month Percent Change  381 non-null    float64
 25  APU0000701111 Original Data Value      380 non-null    float64
 26  APU0000701111 1-Month Percent Change   379 non-null    float64
 27  APU0000701111 3-Month Percent Change   379 non-null    float64
 28  APU0000701111 12-Month Percent Change  379 non-null    float64
 29  APU0000709112 Original Data Value      315 non-null    float64
 30  APU0000709112 1-Month Percent Change   314 non-null    float64
 31  APU0000709112 3-Month Percent Change   312 non-null    float64
 32  APU0000709112 12-Month Percent Change  303 non-null    float64
 33  APU0000711311 Original Data Value      295 non-null    float64
 34  APU0000711311 1-Month Percent Change   274 non-null    float64
 35  APU0000711311 3-Month Percent Change   243 non-null    float64
 36  APU0000711311 12-Month Percent Change  280 non-null    float64
 37  APU0000701312 Original Data Value      356 non-null    float64
 38  APU0000701312 1-Month Percent Change   354 non-null    float64
 39  APU0000701312 3-Month Percent Change   352 non-null    float64
 40  APU0000701312 12-Month Percent Change  343 non-null    float64
 41  APU0000712311 Original Data Value      378 non-null    float64
 42  APU0000712311 1-Month Percent Change   376 non-null    float64
 43  APU0000712311 3-Month Percent Change   375 non-null    float64
 44  APU0000712311 12-Month Percent Change  375 non-null    float64
 45  APU000072610 Original Data Value       381 non-null    float64
 46  APU000072610 1-Month Percent Change    381 non-null    float64
 47  APU000072610 3-Month Percent Change    381 non-null    float64
 48  APU000072610 12-Month Percent Change   381 non-null    float64
 49  APU000072511 Original Data Value       381 non-null    float64
 50  APU000072511 1-Month Percent Change    381 non-null    float64
 51  APU000072511 3-Month Percent Change    381 non-null    float64
 52  APU000072511 12-Month Percent Change   381 non-null    float64
 53  APU00007471A Original Data Value       381 non-null    float64
 54  APU00007471A 1-Month Percent Change    381 non-null    float64
 55  APU00007471A 3-Month Percent Change    381 non-null    float64
 56  APU00007471A 12-Month Percent Change   381 non-null    float64
 57  APU000074714 Original Data Value       381 non-null    float64
 58  APU000074714 1-Month Percent Change    381 non-null    float64
 59  APU000074714 3-Month Percent Change    381 non-null    float64
 60  APU000074714 12-Month Percent Change   381 non-null    float64
dtypes: datetime64[ns](1), float64(60)
memory usage: 183.1 KB

In [9]:
# cpi.set_index('Date', drop=True, inplace=True)

### Adressing Column Names

To clear confusion of labels I will change all names to their proper categories. APU### is directly from the Bureau of Labor Statistics website. This will be used moving forward in all joins, EDA, and wrangling work.

In [12]:
cpi.columns = cpi.columns.str.replace('APU0000704111', 'Bacon')
cpi.columns = cpi.columns.str.replace('APU0000711211', 'Bananas')
cpi.columns = cpi.columns.str.replace('APU0000702111', 'Bread')
cpi.columns = cpi.columns.str.replace('APU0000706111', 'Chicken')
cpi.columns = cpi.columns.str.replace('APU0000717311', 'Coffee')
cpi.columns = cpi.columns.str.replace('APU0000708111', 'Eggs')
cpi.columns = cpi.columns.str.replace('APU0000701111', 'Flour')
cpi.columns = cpi.columns.str.replace('APU0000709112', 'Milk')
cpi.columns = cpi.columns.str.replace('APU0000711311', 'Oranges')
cpi.columns = cpi.columns.str.replace('APU0000701312', 'Rice')
cpi.columns = cpi.columns.str.replace('APU0000712311', 'Tomatoes')
cpi.columns = cpi.columns.str.replace('APU000072610', 'Electricity_CPI')
cpi.columns = cpi.columns.str.replace('APU000072511', 'Fuel_Oil_#2')
cpi.columns = cpi.columns.str.replace('APU00007471A', 'Gasoline_all_types')
cpi.columns = cpi.columns.str.replace('APU000074714', 'Gasoline_unleaded')

Confirmation of changes

In [13]:
cpi.head()

,Date,Bacon Original Data Value,Bacon 1-Month Percent Change,Bacon 3-Month Percent Change,Bacon 12-Month Percent Change,Bananas Original Data Value,Bananas 1-Month Percent Change,Bananas 3-Month Percent Change,Bananas 12-Month Percent Change,Bread Original Data Value,...,Fuel_Oil_#2 3-Month Percent Change,Fuel_Oil_#2 12-Month Percent Change,Gasoline_all_types Original Data Value,Gasoline_all_types 1-Month Percent Change,Gasoline_all_types 3-Month Percent Change,Gasoline_all_types 12-Month Percent Change,Gasoline_unleaded Original Data Value,Gasoline_unleaded 1-Month Percent Change,Gasoline_unleaded 3-Month Percent Change,Gasoline_unleaded 12-Month Percent Change
0,1990-01-01,1.966,0.5,11.2,8.9,0.429,3.1,-0.7,8.9,0.689,...,41.9,42.6,1.090,5.8,1.8,15.5,1.042,6.3,1.5,13.5
1,1990-02-01,2.009,2.2,10.4,11.7,0.492,14.7,13.1,18.6,0.701,...,12.0,15.2,1.086,-0.4,3.8,13.7,1.037,-0.5,3.8,12.0
2,1990-03-01,1.991,-0.9,1.8,11.4,0.500,1.6,20.2,11.1,0.680,...,0.9,10.8,1.076,-0.9,4.5,10.5,1.023,-1.4,4.4,8.8
3,1990-04-01,1.979,-0.6,0.7,13.3,0.481,-3.8,12.1,-8.0,0.686,...,-23.1,7.1,1.096,1.9,0.6,-0.2,1.044,2.1,0.2,-2.0
4,1990-05-01,2.044,3.3,1.7,21.7,0.462,-4.0,-6.1,-11.5,0.678,...,-6.9,7.3,1.114,1.6,2.6,-3.3,1.061,1.6,2.3,-5.2

Checking null values to see what may need to be addressed. I will address null values when all joins are complete into the final dataset.

In [15]:
(cpi.isnull().sum()/len(cpi)).sort_values(ascending=False)

Oranges 3-Month Percent Change     0.367188
Oranges 1-Month Percent Change     0.286458
Oranges 12-Month Percent Change    0.270833
Oranges Original Data Value        0.231771
Milk 12-Month Percent Change       0.210938
                                     ...
Bread 12-Month Percent Change      0.007812
Eggs Original Data Value           0.007812
Eggs 1-Month Percent Change        0.007812
Eggs 3-Month Percent Change        0.007812
Date                               0.000000
Length: 61, dtype: float64

Briefly, we can see that oranges are the highest percentage of null values that will need to be addressed later.

In [18]:
cpi.to_csv('CPI_cleaned.csv')

This cleaned version of Consumer Price Index will now be exported to a CSV for futre joining to the other datasets to complete the wrangle. The next step will be joining EIA, CPI, and INF (inflation index).